# Generated by Django 5.2.14 on 2026-05-25 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('funcao_quimica', models.CharField(help_text='Ex: Conservante, Emulsificante', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Substancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cas_number', models.CharField(help_text='Identificador químico universal', max_length=50, unique=True)),
                ('nivel_risco', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Nota de 1 a 5')),
                ('mecanismo_acao', models.TextField()),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SugestaoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa_tecnica', models.TextField()),
                ('origem_sugestao', models.CharField(default='Base de Dados Flora', max_length=100)),
                ('confianca', models.FloatField(default=1.0, help_text='Grau de certeza estatística do algoritmo/médico')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDesregulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Estrogênico, Androgênico, Tireoidiano', max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(help_text='Código GTIN/EAN', max_length=13, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('descricao', models.TextField(blank=True)),
                ('fabricante', models.CharField(max_length=150)),
                ('nota_flora', models.FloatField(default=5.0, help_text='Calculada dinamicamente de 1 a 5 (RN03)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracao_estimada', models.FloatField(help_text='Valor numérico bruto')),
                ('unidade_concentracao', models.CharField(default='%', help_text='Ex: %, ppm, mg/kg', max_length=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.ingrediente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao', to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_artigo', models.CharField(max_length=255)),
                ('autores', models.TextField()),
                ('ano_publicacao', models.IntegerField()),
                ('link_doi', models.URLField()),
                ('instituicao_fonte', models.CharField(max_length=255)),
                ('arquivo_artigo', models.FileField(blank=True, null=True, upload_to='artigos_cientificos/')),
                ('substancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='produtos.substancia')),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='substancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes', to='produtos.substancia'),
        ),
    ]
