# Generated by Django 5.2.14 on 2026-06-01 11:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('funcao_quimica', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Substancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cas_number', models.CharField(max_length=50, unique=True)),
                ('nivel_risco', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mecanismo_acao', models.TextField()),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Substância',
                'verbose_name_plural': 'Substâncias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SugestaoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa_tecnica', models.TextField()),
                ('origem_sugestao', models.CharField(default='Base de Dados Flora', max_length=100)),
                ('confianca', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='TipoDesregulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Desregulador',
                'verbose_name_plural': 'Tipos de Desreguladores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(max_length=14, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('descricao', models.TextField(blank=True)),
                ('fabricante', models.CharField(blank=True, max_length=150)),
                ('nota_flora', models.FloatField(default=5.0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome', 'marca'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracao_estimada', models.FloatField(default=0.0)),
                ('unidade_concentracao', models.CharField(default='%', max_length=20)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.ingrediente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Ingrediente do Produto',
                'verbose_name_plural': 'Ingredientes dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_artigo', models.CharField(max_length=255)),
                ('autores', models.TextField()),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('link_doi', models.URLField(blank=True)),
                ('instituicao_fonte', models.CharField(blank=True, max_length=255)),
                ('arquivo_artigo', models.FileField(blank=True, null=True, upload_to='artigos_cientificos/')),
                ('substancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='produtos.substancia')),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='substancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes', to='produtos.substancia'),
        ),
    ]
