# Generated by Django 5.2.14 on 2026-06-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestaotroca',
            name='especialista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.especialista'),
        ),
        migrations.AddField(
            model_name='sugestaotroca',
            name='produto_risco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_de_substituicao', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='sugestaotroca',
            name='produto_seguro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas_seguras', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='substancia',
            name='tipo_desregulador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substancias', to='produtos.tipodesregulador'),
        ),
        migrations.AlterUniqueTogether(
            name='produtoingrediente',
            unique_together={('produto', 'ingrediente')},
        ),
    ]
