# Generated by Django 5.2.14 on 2026-06-01 10:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome', 'marca']},
        ),
        migrations.AlterModelOptions(
            name='substancia',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='tipodesregulador',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='funcao_quimica',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nota_flora',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='produtoingrediente',
            name='concentracao_estimada',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='produtoingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.ingrediente'),
        ),
        migrations.AlterField(
            model_name='produtoingrediente',
            name='unidade_concentracao',
            field=models.CharField(default='%', max_length=20),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='ano_publicacao',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='instituicao_fonte',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='link_doi',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='substancia',
            name='cas_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='substancia',
            name='nivel_risco',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sugestaotroca',
            name='confianca',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tipodesregulador',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tipodesregulador',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
