# Generated by Django 5.2.14 on 2026-06-08 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_produtos', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Comentário de produto',
                'verbose_name_plural': 'Comentários de produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CurtidaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='produtos.comentarioproduto', verbose_name='Comentário')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_curtidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Curtida',
                'verbose_name_plural': 'Curtidas',
                'constraints': [models.UniqueConstraint(fields=('comentario', 'usuario'), name='curtida_unica_por_usuario')],
            },
        ),
    ]
