# Generated by Django 5.2.14 on 2026-06-01 11:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=120, verbose_name='Nome da cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['uf__sigla', 'nome_cidade'],
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(max_length=80, verbose_name='Nome do estado')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_usuario', models.CharField(choices=[('USUARIA', 'Usuária'), ('ESPECIALISTA', 'Especialista'), ('ADMIN', 'Administrador')], default='USUARIA', max_length=15, verbose_name='Tipo de usuário')),
                ('apelido', models.CharField(blank=True, max_length=50, verbose_name='Apelido')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto de perfil')),
                ('registro_profissional', models.CharField(blank=True, max_length=60, verbose_name='Registro profissional')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
                ('especialidade', models.CharField(blank=True, max_length=120, verbose_name='Especialidade')),
                ('nivel_acesso', models.CharField(blank=True, max_length=120, verbose_name='Nível de acesso')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('ultimo_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.pessoa',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.pessoa',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'verbose_name': 'Usuária',
                'verbose_name_plural': 'Usuárias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.pessoa',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='usuarios.uf', verbose_name='UF'),
        ),
        migrations.CreateModel(
            name='PerfilHormonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso_contraceptivo', models.BooleanField(default=False, verbose_name='Usa contraceptivo?')),
                ('condicao_hormonal', models.CharField(blank=True, max_length=255, verbose_name='Condição hormonal')),
                ('ciclo_regular', models.BooleanField(default=True, verbose_name='Ciclo regular?')),
                ('duracao_ciclo', models.PositiveIntegerField(default=28, verbose_name='Duração média do ciclo')),
                ('fluxo_menstrual', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('INTENSO', 'Intenso')], default='MODERADO', max_length=20, verbose_name='Fluxo menstrual')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('peso_sensibilidade', models.FloatField(default=1.0, verbose_name='Peso de sensibilidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_hormonal', to='usuarios.usuario', verbose_name='Usuária')),
            ],
            options={
                'verbose_name': 'Perfil Hormonal',
                'verbose_name_plural': 'Perfis Hormonais',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('nome_cidade', 'uf')},
        ),
    ]
