# Generated by Django 5.2.14 on 2026-06-01 10:45

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['uf__sigla', 'nome_cidade']},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='uf',
            options={'ordering': ['sigla'], 'verbose_name': 'UF', 'verbose_name_plural': 'UFs'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='nivel_acesso',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome_cidade',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='especialidade',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='registro_profissional',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='perfilhormonal',
            name='condicao_hormonal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilhormonal',
            name='duracao_ciclo',
            field=models.PositiveIntegerField(default=28),
        ),
        migrations.AlterField(
            model_name='perfilhormonal',
            name='fluxo_menstrual',
            field=models.CharField(choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('INTENSO', 'Intenso')], default='MODERADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='uf',
            name='nome_estado',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('nome_cidade', 'uf')},
        ),
    ]
