# Generated by Django 5.2.14 on 2026-05-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_alerta', models.TextField()),
                ('nivel_gravidade', models.CharField(choices=[('VERDE', 'Verde (Abaixo de 50%)'), ('AMARELO', 'Amarelo (Entre 50% e 75%)'), ('VERMELHO', 'Vermelho (Acima de 75%)')], max_length=10)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArmarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia_uso', models.FloatField(choices=[(3.0, 'Diário'), (1.0, 'Semanal'), (0.5, 'Esporádico')], default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='CicloMenstrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('duracao', models.IntegerField(help_text='Duração em dias calculada automaticamente')),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_estrogenica', models.FloatField(default=0.0)),
                ('carga_androgenica', models.FloatField(default=0.0)),
                ('carga_tireoidiana', models.FloatField(default=0.0)),
                ('carga_total', models.FloatField(default=0.0)),
                ('data_calculo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExposicaoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_contribuicao', models.FloatField(help_text='Contribuição fracionada desta substância no cálculo total')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('tipo_notificacao', models.CharField(max_length=100)),
                ('lida', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ocorrencia', models.DateField()),
                ('intensidade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Escala de dor/incômodo de 1 a 5')),
                ('fase_ciclo', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
