# Generated by Django 5.2.14 on 2026-06-01 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_alerta', models.TextField()),
                ('nivel_gravidade', models.CharField(choices=[('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('VERMELHO', 'Vermelho')], max_length=10)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta de Risco',
                'verbose_name_plural': 'Alertas de Riscos',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ArmarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia_uso', models.FloatField(choices=[(3.0, 'Diário'), (1.0, 'Semanal'), (0.5, 'Esporádico')], default=1.0)),
            ],
            options={
                'verbose_name': 'Item do Armário',
                'verbose_name_plural': 'Itens do Armário',
            },
        ),
        migrations.CreateModel(
            name='CicloMenstrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('duracao', models.PositiveIntegerField(default=5)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ciclo Menstrual',
                'verbose_name_plural': 'Ciclos Menstruais',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Exposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_estrogenica', models.FloatField(default=0.0)),
                ('carga_androgenica', models.FloatField(default=0.0)),
                ('carga_tireoidiana', models.FloatField(default=0.0)),
                ('carga_total', models.FloatField(default=0.0)),
                ('data_calculo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exposição',
                'verbose_name_plural': 'Exposições',
                'ordering': ['-data_calculo'],
            },
        ),
        migrations.CreateModel(
            name='ExposicaoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_contribuicao', models.FloatField()),
            ],
            options={
                'verbose_name': 'Detalhe da Exposição',
                'verbose_name_plural': 'Detalhes da Exposição',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('tipo_notificacao', models.CharField(max_length=100)),
                ('lida', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ocorrencia', models.DateField()),
                ('intensidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fase_ciclo', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de Sintoma',
                'verbose_name_plural': 'Registro de Sintomas',
                'ordering': ['-data_ocorrencia'],
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': 'Sintomas',
            },
        ),
    ]
