# Generated by Django 5.2.14 on 2026-05-25 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0002_initial'),
        ('saude', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertarisco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_risco', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='armarioitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='armarioitem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armario', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='ciclomenstrual',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='exposicao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_exposicoes', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='exposicaodetalhe',
            name='exposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='saude.exposicao'),
        ),
        migrations.AddField(
            model_name='exposicaodetalhe',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='exposicaodetalhe',
            name='substancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.substancia'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diario_sintomas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='sintoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude.sintoma'),
        ),
        migrations.AlterUniqueTogether(
            name='armarioitem',
            unique_together={('usuario', 'produto')},
        ),
    ]
