# Generated by Django 5.2.14 on 2026-06-01 10:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_categoria_options_alter_ingrediente_options_and_more'),
        ('saude', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertarisco',
            options={'ordering': ['-data_emissao']},
        ),
        migrations.AlterModelOptions(
            name='ciclomenstrual',
            options={'ordering': ['-data_inicio']},
        ),
        migrations.AlterModelOptions(
            name='exposicao',
            options={'ordering': ['-data_calculo']},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data_envio']},
        ),
        migrations.AlterModelOptions(
            name='registrosintoma',
            options={'ordering': ['-data_ocorrencia']},
        ),
        migrations.AlterField(
            model_name='alertarisco',
            name='nivel_gravidade',
            field=models.CharField(choices=[('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('VERMELHO', 'Vermelho')], max_length=10),
        ),
        migrations.AlterField(
            model_name='armarioitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_no_armario', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='ciclomenstrual',
            name='duracao',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='exposicaodetalhe',
            name='valor_contribuicao',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='registrosintoma',
            name='fase_ciclo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrosintoma',
            name='intensidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='registrosintoma',
            name='sintoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='saude.sintoma'),
        ),
        migrations.AlterField(
            model_name='sintoma',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
